Repository moevm/MSE-2023-image-ecology-12, pull requests merged in 2023-03, with the labels that each got.

#2 [WIP] template changes
  README.md
Labels: research

#18 [dev] Docker compose structure init
  docker-compose.yml
  nginx/nginx.conf
  nginx/templates/default.conf.conf
  server/Dockerfile
  server/main.py
  worker/Dockerfile
  worker/main.py
Labels: improvement

#15 [test] Geotiff slicing to fragments for display.
  worker/image_processing/geotiff_slicer/geotiff2png.py
  worker/image_processing/geotiff_slicer/slice2tiles.py
  worker/image_processing/geotiff_slicer/test.py
  worker/image_processing/geotiff_slicer/test/img/sample.tif
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/layers-2x.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/layers.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/marker-icon-2x.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/marker-icon.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/marker-shadow.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet-src.esm.js
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet-src.esm.js.map
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet-src.js
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet-src.js.map
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet.css
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet.js
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet.js.map
  worker/image_processing/geotiff_slicer/test/output/sample.png
  worker/image_processing/geotiff_slicer/test/output/sample.png.aux.xml
  worker/image_processing/geotiff_slicer/test/output/sample/11/1048/1373.png
  worker/image_processing/geotiff_slicer/test/output/sample/11/1049/1373.png
  worker/image_processing/geotiff_slicer/test/output/sample/12/2097/2746.png
  worker/image_processing/geotiff_slicer/test/output/sample/12/2097/2747.png
  worker/image_processing/geotiff_slicer/test/output/sample/12/2098/2746.png
  worker/image_processing/geotiff_slicer/test/output/sample/12/2098/2747.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4194/5492.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4194/5493.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4194/5494.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4194/5495.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4195/5492.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4195/5493.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4195/5494.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4195/5495.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4196/5492.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4196/5493.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4196/5494.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4196/5495.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4197/5492.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4197/5493.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4197/5494.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4197/5495.png
  worker/image_processing/geotiff_slicer/test/output/sample/googlemaps.html
  worker/image_processing/geotiff_slicer/test/output/sample/leaflet.html
  worker/image_processing/geotiff_slicer/test/output/sample/openlayers.html
  worker/image_processing/geotiff_slicer/test/output/sample/tilemapresource.xml
Labels: task

#14 [dev] Geotiff slicing to fragments for display
  worker/image_processing/geotiff_slicer/geotiff2png.py
  worker/image_processing/geotiff_slicer/slice2tiles.py
  worker/image_processing/geotiff_slicer/test.py
  worker/image_processing/geotiff_slicer/test/img/sample.tif
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/layers-2x.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/layers.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/marker-icon-2x.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/marker-icon.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/images/marker-shadow.png
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet-src.esm.js
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet-src.esm.js.map
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet-src.js
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet-src.js.map
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet.css
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet.js
  worker/image_processing/geotiff_slicer/test/output/leaflet/leaflet.js.map
  worker/image_processing/geotiff_slicer/test/output/sample.png
  worker/image_processing/geotiff_slicer/test/output/sample.png.aux.xml
  worker/image_processing/geotiff_slicer/test/output/sample/11/1048/1373.png
  worker/image_processing/geotiff_slicer/test/output/sample/11/1049/1373.png
  worker/image_processing/geotiff_slicer/test/output/sample/12/2097/2746.png
  worker/image_processing/geotiff_slicer/test/output/sample/12/2097/2747.png
  worker/image_processing/geotiff_slicer/test/output/sample/12/2098/2746.png
  worker/image_processing/geotiff_slicer/test/output/sample/12/2098/2747.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4194/5492.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4194/5493.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4194/5494.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4194/5495.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4195/5492.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4195/5493.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4195/5494.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4195/5495.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4196/5492.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4196/5493.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4196/5494.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4196/5495.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4197/5492.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4197/5493.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4197/5494.png
  worker/image_processing/geotiff_slicer/test/output/sample/13/4197/5495.png
  worker/image_processing/geotiff_slicer/test/output/sample/googlemaps.html
  worker/image_processing/geotiff_slicer/test/output/sample/leaflet.html
  worker/image_processing/geotiff_slicer/test/output/sample/openlayers.html
  worker/image_processing/geotiff_slicer/test/output/sample/tilemapresource.xml
Labels: task

#20 [test] Detector init
  worker/detector/forest2.jpg
  worker/detector/forest2_1.jpg
  worker/detector/main.py
Labels: improvement

#19 [dev] Detector init
  worker/detector/forest2.jpg
  worker/detector/forest2_1.jpg
  worker/detector/main.py
Labels: improvement
